version: '3.9'

services:
  app:
    container_name: genshin-app
    build: .
    command: npm run start
    env_file:
      - .env
    volumes:
      - .:/usr/app
    networks:
      - genshin-net
  postgres:
    image: postgres
    container_name: genshin-postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - genshin-net

networks:
  genshin-net:
    driver: bridge