version: '3.9'

services:
  app:
    container_name: genshin-app
    build: .
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - genshin-net
    environment:
      - TZ=America/Sao_Paulo 

  postgres:
    image: postgres
    container_name: genshin-postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: genshin_builds
      
    
    volumes:
      - /var/lib/postgresql/data # cria e monta um volume anônimo no contêiner
    networks:
      - genshin-net

networks:
  genshin-net:
    driver: bridge